name: mlops-student-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pandas
  - numpy
  - scikit-learn
  - joblib
  - matplotlib
  - seaborn
  - shap
  - lime
  - jupyter
  - ipykernel
  - pytest
  - pytest-cov
  - pyyaml
  - python-dotenv
  - fastapi
  - uvicorn
  - pydantic
  - httpx
  - pip
  - pip:
    - wandb